#!/usr/bin/env node
/**
 * CDO §8 — Font subsetting for nav glyphs.
 * Produces a small woff2 per CJK locale containing only the chars used in
 * the navigation bar (≈100 glyphs). The browser loads these tiny files eagerly
 * via @font-face unicode-range; the full CJK fonts defer normally.
 *
 * Requires: pyftsubset (pip install fonttools brotli)
 * Output:   public/fonts/subset/  (woff2 + nav-fonts.css)
 */

import { execSync } from 'child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root  = resolve(__dir, '..');
const outDir = resolve(root, 'public/fonts/subset');

// ---------------------------------------------------------------------------
// Nav chars per locale — extracted from src/components/Nav.astro
// Includes: nav labels, taglines, app labels, lang switcher labels
// ---------------------------------------------------------------------------
const NAV_CHARS = {
  'zh-hk': '首頁吞嚥困難指南灣區標準食譜庫資源下載數碼工具專業人士關於我們香港照護知識中心免費臨床繁體中文',
  'zh-cn': '首页吞咽困难指南湾区标准食谱库资源下载数码工具专业人士关于我们香港照护知识中心免费临床简体中文',
  'ja':    'ホームレシピ集リソースツール専門家向け私たちについて嚥下障害ガイド介護食ナレッジセンター無料アプリ日本語',
};

// fontsource woff2 sources that cover the full CJK block for each locale
const FONT_SOURCES = {
  'zh-hk': {
    family:  'Noto Sans HK',
    srcFile: 'node_modules/@fontsource/noto-sans-hk/files/noto-sans-hk-chinese-hongkong-400-normal.woff2',
    outFile: 'noto-sans-hk-nav-400.woff2',
  },
  'zh-cn': {
    family:  'Noto Sans SC',
    srcFile: 'node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-chinese-simplified-400-normal.woff2',
    outFile: 'noto-sans-sc-nav-400.woff2',
  },
  'ja': {
    family:  'Noto Sans JP',
    srcFile: 'node_modules/@fontsource/noto-sans-jp/files/noto-sans-jp-japanese-400-normal.woff2',
    outFile: 'noto-sans-jp-nav-400.woff2',
  },
};

// ---------------------------------------------------------------------------
// Verify pyftsubset is on PATH
// ---------------------------------------------------------------------------
try {
  execSync('pyftsubset --help', { stdio: 'ignore' });
} catch {
  console.error('ERROR: pyftsubset not found. Install with: pip install fonttools brotli');
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

const cssBlocks = [];

for (const [locale, chars] of Object.entries(NAV_CHARS)) {
  const cfg = FONT_SOURCES[locale];
  const srcAbs = resolve(root, cfg.srcFile);
  const outAbs = resolve(outDir, cfg.outFile);

  if (!existsSync(srcAbs)) {
    console.error(`[${locale}] Source not found: ${cfg.srcFile}`);
    process.exit(1);
  }

  // Unique codepoints in the nav string (CJK + kana only — skip ASCII)
  const codepoints = [...new Set([...chars])]
    .filter(c => c.codePointAt(0) > 0x007F)          // exclude ASCII
    .map(c => `U+${c.codePointAt(0).toString(16).toUpperCase()}`);

  if (codepoints.length === 0) {
    console.warn(`[${locale}] No non-ASCII chars — skipping`);
    continue;
  }

  const unicodeArg = codepoints.join(',');
  console.log(`[${locale}] Subsetting ${codepoints.length} glyphs from ${cfg.srcFile.split('/').pop()}…`);

  try {
    execSync(
      `pyftsubset "${srcAbs}" --unicodes="${unicodeArg}" --output-file="${outAbs}" --flavor=woff2`,
      { stdio: 'pipe' }
    );
  } catch (err) {
    console.error(`[${locale}] pyftsubset failed: ${err.stderr?.toString() ?? err.message}`);
    process.exit(1);
  }

  const sizeKB = (readFileSync(outAbs).length / 1024).toFixed(1);
  console.log(`[${locale}] → ${cfg.outFile} (${sizeKB} KB)`);

  // Build the @font-face block for the subset.
  // unicode-range lists ONLY the chars we inlined so the browser never fetches
  // this file for any other codepoint.
  const unicodeRange = codepoints.join(',\n               ');
  cssBlocks.push(`/* ${locale} — nav-glyph subset (${codepoints.length} glyphs, ${sizeKB} KB) */
@font-face {
  font-family: '${cfg.family}';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('/fonts/subset/${cfg.outFile}') format('woff2');
  unicode-range: ${unicodeRange};
}`);
}

// ---------------------------------------------------------------------------
// Write nav-fonts.css
// ---------------------------------------------------------------------------
const header = `/*
 * Auto-generated by scripts/subset-fonts.mjs — DO NOT EDIT BY HAND.
 * CDO §8: nav-glyph CJK subsets loaded eagerly; full fonts defer.
 * Regenerate: node scripts/subset-fonts.mjs
 */

`;

const cssPath = resolve(outDir, 'nav-fonts.css');
writeFileSync(cssPath, header + cssBlocks.join('\n\n') + '\n');

console.log(`\nWrote ${cssBlocks.length} @font-face rules → public/fonts/subset/nav-fonts.css`);
console.log('Add this to your BaseLayout <head>:');
console.log('  <link rel="stylesheet" href="/fonts/subset/nav-fonts.css" />');
console.log('  (or inline the @font-face rules directly in global.css for zero-RTT)');
